"""
Django settings for OpsManage project.

Generated by 'django-admin startproject' using Django 1.9.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os, sys
import djcelery
from celery import platforms
from kombu import Queue, Exchange

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# settings for the stupid file uploading
media_url = '/upload/'
media_root = os.path.join(BASE_DIR, 'media')

# ansible role root tree USEEASE
# ROLE_TREE_ROOT = os.path.join(BASE_DIR, 'roles')
ROLE_TREE_ROOT = '/etc/ansible/roles'
ROLE_TREE_ROOT_ALIAS = 'Role Tree'

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

''' celery config '''
djcelery.setup_loader()
# BROKER_URL = 'redis://192.168.210.14:6379/3'
BROKER_URL = 'redis://:nz757(b$3gF8@127.0.0.1:6379/5'
CELERY_RESULT_BACKEND = 'djcelery.backends.database.DatabaseBackend'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_ACCEPT_CONTENT = ['json', 'pickle']
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24
CELERYD_MAX_TASKS_PER_CHILD = 40
CELERY_TRACK_STARTED = True
CELERY_TIMEZONE = 'Asia/Shanghai'
platforms.C_FORCE_ROOT = True

# ansible playbook path
PLAYBOOK_PATH = '/etc/ansible/playbook'
# celery route config
CELERY_IMPORTS = ("crontask.views.ansible_celery_task")
CELERY_QUEUES = (
    Queue('default', Exchange('default'), routing_key='default'),
    Queue('ansible', Exchange('ansible'), routing_key='ansible_playbook'),
)
CELERY_ROUTES = {
    'crontask.views.ansible_celery_task.AnsiblePlayBook': {'queue': 'ansible', 'routing_key': 'ansible_playbook'},
}
CELERY_DEFAULT_QUEUE = 'default'
CELERY_DEFAULT_EXCHANGE_TYPE = 'direct'
CELERY_DEFAULT_ROUTING_KEY = 'default'

# REDSI_KWARGS_LPUSH = {"host":'192.168.210.14','port':6379,'db':3}
# REDSI_KWARGS_LPUSH = {"host":'127.0.0.1','port':6379,'db':3}
REDSI_KWARGS_LPUSH = {"host": '127.0.0.1', 'port': 6379, 'db': 3, 'password': 'nz757(b$3gF8'}
REDSI_LPUSH_POOL = None
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kd8f&jx1h^1m-uldfdo3d#10d9mbc-ijjz!tozusy@aw#h+875'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'OpsManage',
    'rest_framework',
    'djcelery',
    'elfinder',
    'webssh',
    'asset',
    'log',
    'crontask',
    'api',
    'users',
    'workflow'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #    'django.middleware.csrf.CsrfViewMiddleware',
    #     'django.middleware.csrf.CsrfResponseMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    #     'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.DjangoFilterBackend',
    #     ),
}

ROOT_URLCONF = 'OpsManage.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': ["E:\\MyPros\\OpsManage\\OpsManage\\static\\"],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

WSGI_APPLICATION = 'OpsManage.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'opsmanage',
        'USER': 'root',
		  'PASSWORD': '123456',
          'HOST': ''
         # 'PASSWORD': 'Mysql123',
         # 'HOST': '192.168.2.168'
        #         'ENGINE': 'django.db.backends.sqlite3',
        #         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'OpsManage/static/'),
)
TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'OpsManage/templates'),
)
# default URL
LOGIN_URL = '/login'
# set Session
SESSION_SAVE_EVERY_REQUEST = True
# set Session Timeout unit:second
SESSION_COOKIE_AGE = 60 * 60 * 30
# she close browser Session invalid
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# '''GateOne Setting'''

# use gateone ssl or not
GATEONE_SSL = True

# if GATEONE_SSL == True, here should be "https", KEY and SECRET should be set.
GATEONE_SERVER = 'https://192.168.2.168:18888'

GATEONE_KEY = 'MzRkNWM1MGFhOGUzNDJiN2IzNTk4NmI1MzM5Njc0ZmYyZ'
GATEONE_SECRET = 'YzNhNDA4ODE5ZTJhNGRlMzg1NmQwMzkxNjQ4MjY2MzczM'
